name: Release - Test environment
on:
  push:
    branches:
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CI: true

jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install -r
      - name: Build test environment
        run: pnpm build
      - name: Config aws credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Upload static file to aws s3
        run: aws s3 cp ./dist/ s3://beta.oooo.money/ --exclude "*.html" --exclude "*.map" --exclude ".DS_Store" --recursive
      - name: Upload html file to aws s3
        run: aws s3 cp ./dist/ s3://beta.oooo.money/ --exclude "*" --include "*.html" --cache-control no-cache --recursive
